/* ===== Settings: account, engine defaults, MCP server for AI coders, storage ===== */
const MCP_TOOLS = [['expertstream_status', 'RAM, disk, CPU, engine, loaded model'], ['recommend_models', 'rank models that fit this device (up to 250B) and give the setup steps'], ['plan_capacity', 'will a model of this size fit, and how fast would it run'], ['list_local_models', 'models on the device with a can-it-run verdict'], ['search_huggingface', 'search GGUF models, flags supported architectures'], ['list_repo_files', 'list the GGUF files of a repository'], ['inspect_model', 'read a model header without downloading it'], ['download_model', 'resumable download from Hugging Face'], ['download_status', 'progress of a download'], ['load_model', 'load a model into the engine'], ['generate', 'ask the loaded model'], ['chat_reset', 'start a new conversation'], ['benchmark', 'measure tokens per second'], ['unload_model', 'free memory'], ['import_pack', 'convert a split GGUF MoE for very large models'], ['open_web_ui', 'start this website on the device'], ['connect_huggingface', 'link a Hugging Face account: the AI shows a code, you click Allow'], ['connect_huggingface_finish', 'finish the Hugging Face sign-in']];
const REPO = 'https://github.com/Tharunmaks/Stream-.git', BRANCH = 'claude/expertstream-moe-android-oegt59';
function cmdBlock(text) { return h('div', { style: 'position:relative' }, h('pre', { class: 'cmd' }, text), h('button', { class: 'btn sm', style: 'position:absolute;top:6px;right:6px', onclick: () => copyText(text) }, 'Copy')); }
function slider(key, label, min, max, step, def, fmt, note) { const v = h('b', { class: 'mono' }, fmt(store.get(key, def))); return h('label', { class: 'field' }, h('span', { class: 'row', style: 'justify-content:space-between' }, label, v), h('input', { type: 'range', min, max, step, value: store.get(key, def), oninput: e => { store.set(key, +e.target.value); v.textContent = fmt(+e.target.value); } }), note ? h('span', { class: 'dim', style: 'font-size:12px' }, note) : null); }
async function renderSettings() {
  const box = $('#set-body'); box.replaceChildren();
  box.append(accountCard(() => { if (!$('#settings').hidden) renderSettings(); }));
  // engine defaults
  box.append(h('div', { class: 'card' }, h('h3', {}, 'Engine defaults'), h('div', { class: 'grid2' }, slider('temp', 'Creativity (temperature)', 0, 1.5, .05, .7, v => v.toFixed(2), '0 = always the most likely word'), slider('max', 'Longest answer (tokens)', 32, 1024, 32, 256, v => v), slider('ctx', 'Chat memory (tokens)', 256, 4096, 256, 1024, v => v, 'applies when a model loads'), slider('cache', 'Expert cache (MB)', 64, 1024, 32, 384, v => v + ' MB', 'applies when a model loads'))));
  // MCP
  const tokOpt = h('input', { type: 'checkbox', id: 'mcp-tok' }), cmdWrap = h('div', { class: 'stack' });
  const drawCmd = () => {
    const withTok = tokOpt.checked && HFAcct.token, env = withTok ? ` -e HF_TOKEN=${HFAcct.token}` : '';
    cmdWrap.replaceChildren(
      h('div', { class: 'step' }, h('b', {}, '1'), h('div', { class: 'stack' }, h('div', {}, h('b', {}, 'Install the engine'), h('span', { class: 'dim' }, '  (Termux, Linux or macOS; needs git, make, a C compiler, Python 3)')), cmdBlock(`git clone -b ${BRANCH} ${REPO}\ncd Stream- && make`))),
      h('div', { class: 'step' }, h('b', {}, '2'), h('div', { class: 'stack' }, h('div', {}, h('b', {}, 'Add it to Claude Code')), cmdBlock(`claude mcp add expertstream${env} -- python3 ~/Stream-/mcp/expertstream_mcp.py --http 8765 --stdio`), h('p', { class: 'dim', style: 'font-size:12.5px' }, '--http 8765 lets this page show the connection status. Remove it if you do not need that.'))),
      h('div', { class: 'step' }, h('b', {}, '3'), h('div', { class: 'stack' }, h('div', {}, h('b', {}, 'Or any other MCP client'), h('span', { class: 'dim' }, '  (.mcp.json / settings)')), cmdBlock(JSON.stringify({ mcpServers: { expertstream: Object.assign({ command: 'python3', args: ['~/Stream-/mcp/expertstream_mcp.py', '--http', '8765', '--stdio'] }, withTok ? { env: { HF_TOKEN: HFAcct.token } } : {}) } }, null, 2)))),
      h('div', { class: 'step' }, h('b', {}, '4'), h('div', { class: 'stack' }, h('div', {}, h('b', {}, 'Ask your AI coder')), cmdBlock('Use expertstream to find the best model that fits this device, download it, load it, and ask it to summarize my README.'))));
  };
  tokOpt.addEventListener('change', drawCmd); drawCmd();
  const stat = h('div', { class: 'note' }, 'Not checked yet.'), chk = h('button', { class: 'btn', onclick: async () => { chk.textContent = 'Checking…'; stat.className = 'note'; try { const r = await fetch('http://127.0.0.1:8765/health', { cache: 'no-store' }); const j = await r.json(); stat.className = 'note ok'; stat.replaceChildren(h('b', {}, 'Connected. '), `${j.tools} tools · RAM free ${j.device.ram_free_mb} MB · disk free ${j.device.disk_free_gb} GB · engine ${j.device.engine ? 'built' : 'NOT built (run make)'} · limit ${j.max_params_b}B parameters`); store.set('mcp', Date.now()); } catch (e) { stat.className = 'note bad'; stat.replaceChildren(h('b', {}, 'Not reachable. '), 'Start it with the command in step 2 (with --http 8765), keep Termux open, and use the same device. Pages opened from claude.ai or another phone cannot see it.'); } chk.textContent = 'Check connection'; stripDraw(); } }, 'Check connection');
  box.append(h('div', { class: 'card hot' }, h('span', { class: 'eyebrow' }, 'For AI coders'), h('h3', {}, 'MCP server: run models from Claude Code'),
    h('p', { class: 'muted', style: 'font-size:14.5px' }, 'Connect an AI coder such as Claude Code and it can search Hugging Face, download, load and run models on this device, and plan on-device AI systems up to 250 billion parameters. No browser needed.'),
    HFAcct.token ? h('label', { class: 'row', style: 'gap:8px;font-size:13.5px' }, tokOpt, 'Include my Hugging Face token in the commands (they will contain a secret)') : null,
    cmdWrap, h('div', { class: 'row' }, chk), stat,
    h('details', { class: 'think' }, h('summary', {}, MCP_TOOLS.length + ' tools the AI gets'), h('div', { class: 'toolgrid', style: 'margin-top:8px' }, MCP_TOOLS.map(([n, d]) => h('div', { class: 'tool' }, h('b', {}, n), h('p', {}, d))))),
    h('p', { class: 'dim', style: 'font-size:12.5px' }, 'Limits: one loaded model at a time; models above 250B parameters are refused; speed depends on your device (see the capacity planner). The server runs only on this device and the status port listens on 127.0.0.1.')));
  // storage
  const usage = await Lib.usage(); let items = []; try { items = await Lib.list(); } catch (e) { }
  box.append(h('div', { class: 'card' }, h('h3', {}, 'Storage and data'), h('div', { class: 'table-box' }, trow('Models saved', String(items.filter(i => i.complete).length)), trow('Used by this site', usage ? fmtB(usage.used) : '?'), trow('Available', usage ? fmtB(usage.quota - usage.used) : '?'), trow('Prompts in history', String(hist.list.length))),
    h('div', { class: 'row' }, h('button', { class: 'btn sm', onclick: () => { hist.list = []; store.set('hist', []); toast('History cleared'); renderSettings(); } }, 'Clear history'), h('button', { class: 'btn sm danger', onclick: async () => { Brain.close(); for (const i of items) await Lib.remove(i.name); toast('All models deleted'); renderSettings(); } }, 'Delete all models'), h('button', { class: 'btn sm danger', onclick: () => { try { Object.keys(localStorage).filter(k => k.startsWith('es2.')).forEach(k => localStorage.removeItem(k)); } catch (e) { } location.reload(); } }, 'Reset everything'))));
  box.append(h('p', { class: 'dim', style: 'font-size:12.5px;text-align:center' }, 'ExpertStream web 2.2 · engine: ' + (Brain.mode || 'idle') + ' · ' + (Brain.native ? 'native server connected' : 'WebAssembly')));
}
pageHooks.settings = renderSettings;
